### ISSUE TITLE
CloudWatch Enhanced Container Insights

### ISSUE THREAD

**Issue by mswishaws** [aws-samples/eks-workshop-v2#899] opened 2024-04-12 03:29 UTC
### Outline the high level topic of the lab

Show how customers can use enhanced container insights for out of the box metric and log dashboard with control plane visibility and filtering mechanisms

### Provide the flow of the lab exercise, including what sample application components will be used

TBD

### What additional AWS infrastructure or EKS addons/components will need to be created or installed to support this lab?

TBD

### What additional software or configuration will be required in the Cloud9 IDE?

TBD

### Are enhancements to the retail sample application required to support this lab exercise?

TBD

**Comment by niallthomson** [comment] 2024-04-19 15:37
Duplicate of #828

**Closed by niallthomson** 2024-04-19 15:37 UTC
