### ISSUE TITLE
Add Estimated Time to Lab modules

### ISSUE THREAD

**Issue by carlolagaac** [aws-samples/eks-workshop-v2#386] opened 2023-03-15 23:23 UTC
### What would you like to be added?

Can we add the estimated time to complete a lab module added for each lab so when we do an online or F2F workshop we can roughly work out the agenda and timings for the day

### Why is this needed?

Helps us plan an agenda when running this workshop

**Comment by svennam92** [comment] 2023-09-14 14:51
Duplicate of #508

**Closed by svennam92** 2023-09-14 14:51 UTC
Labels: enhancement
