### ISSUE TITLE
[Bug]: "make create-infrastructure" and "make shell" fail with yq version installed with current jq version (1.7.1) on Mac OS

### ISSUE THREAD

**Issue by heinrichse** [aws-samples/eks-workshop-v2#1160] opened 2024-10-29 01:25 UTC
### Installation method

Own AWS account

### What happened?

`eks-workshop-v2 % make create-infrastructure
bash hack/create-infrastructure.sh ''
Warning: Defaulting region to us-west-2
jq: error: load/1 is not defined at <top-level>, line 1:
(.. | select(has("file"))) |= (load(.file)) jq: 1 compile error
make: *** [create-infrastructure] Error 3`

### What did you expect to happen?

`make create-infrastructure` and `make shell` to work with updated jq version. (1.7.1) Instead, yq must be updated separately to version 4.44.3 to support these commands. 

### How can we reproduce it?

Run `make create-infrastructure` or `make shell` from Mac OS terminal with jq 1.7.1 installed. 

### EKS version

Kubernetes 1.30.5

**Comment by niallthomson** [comment] 2024-10-29 02:23
This is resolved by ensuring that you have `yq` version 4.X installed. In many cases `yq` is being installed by package managers along with `jq` and pinned to an old version. Explicitly installing `yq` with your respective package manager seems to resolve the issue.

**Comment by pengc99** [comment] 2024-10-31 22:29
@niallthomson, @heinrichse and I were able to reproduce this earlier this week and @niallthomson found the solution.

This is caused by an outdated version of yq that is automatically installed with jq. We tested this with installing jq 1.7.1, which will install an older version of yq that causes this error. To resolve this error, install a separately managed version of yq. Here is the repo for yq - https://github.com/mikefarah/yq

We were able to successfully build and deploy the workshop's infrastructure and test environment (```make create-infrastructure``` and ```make shell```) with jq v1.7.1 and yq v4.44.3 (latest available as of this comment)

**Closed** 2024-12-12 04:03 UTC
Labels: bug
