### ISSUE TITLE
[Bug]: Managed Node Group Graviton Lab doesn't work with eksctl 0.164

### ISSUE THREAD

**Issue by Gungz** [aws-samples/eks-workshop-v2#802] opened 2024-01-31 14:15 UTC
### Installation method

Workshop Studio

### What happened?

When I try to run below command as per lab instruction
```
cat ~/environment/eks-workshop/modules/fundamentals/mng/graviton/nodegroup.yaml \
  | envsubst | eksctl create nodegroup -f -
```

I get an error like below
> 
> ERROR: json: unknown field "AccessConfig"
> 2024-01-31 14:12:52 [ℹ]  1 error(s) occurred and nodegroups haven't been created properly, you may wish to check CloudFormation console
> 2024-01-31 14:12:52 [ℹ]  to cleanup resources, run 'eksctl delete nodegroup --region=ap-southeast-2 --cluster=eks-workshop --name=<name>' for each of the failed nodegroup
> 2024-01-31 14:12:52 [✖]  error getting cluster stack template: failed to parse GetStackTemplate response: json: unknown field "AccessConfig"

### What did you expect to happen?

There's no error and nodegroup graviton is created

### How can we reproduce it?

Just follow the MNG Graviton lab and execute the command as described in What happened?

### Anything else we need to know?

Upgrade to eksctl latest version (0.169.0) fixes the issue, I have tried it.

### EKS version

1.27

**Comment by niallthomson** [comment] 2024-02-01 03:52
@Gungz thanks for raising this. I've been unable to reproduce and this scenario is passing in our automated tests so I'm taking some time to investigate more.

**Comment by Gungz** [comment] 2024-02-01 07:10
OK, that's strange if I have time, I'll try to make video out of it, and my guess probably because 0.164 has not supported AccessConfig which is there in the CloudFormation that is generated upon cluster creation (no idea why it is there) because from eksctl release history it seems AccessConfig is added only in version 0.167.

**Comment by Gungz** [comment] 2024-02-05 03:09
Below is the screen shot @niallthomson.

<img width="1158" alt="Screenshot 2024-02-05 at 10 02 37" src="https://github.com/aws-samples/eks-workshop-v2/assets/442523/6b7e2012-bbbe-4f94-a3fe-f00e88336043">

**Comment by xiangyanw** [comment] 2024-02-18 05:31
I met the same issue when creating a new nodegroup (though it is not exactly the same step as yours). I can fix this issue by upgrading eksctl to the latest version.
`curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
sudo mv /tmp/eksctl /usr/local/bin/eksctl`

**Comment by niallthomson** [comment] 2024-03-09 05:24
This should be resolved with the latest published version

**Closed by niallthomson** 2024-03-09 05:24 UTC
Labels: bug

**Comment by kishoreakshat** [comment] 2024-03-21 17:02
For anyone wondering about this issue while following EKS Finhack workshop, this error comes up because these workshops use latest eksctl version to create the EKS cluster which adds this snippet to the cluster cloudformation template:
```
"AccessConfig": {
          "AuthenticationMode": "API_AND_CONFIG_MAP",
          "BootstrapClusterCreatorAdminPermissions": true
        }
```
and when someoone uses an older eksctl version on their local setup, the old eksctl installation is not able to understand what an AccessConfig is in a CFN template because this feature is new.

Solution: [Update](https://docs.aws.amazon.com/emr/latest/EMR-on-EKS-DevelopmentGuide/setting-up-eksctl.html) your local eksctl installation
