### ISSUE TITLE
[Bug]: Using the latest version of kubectl (1.28.1) breaks "make serve" 

### ISSUE THREAD

**Issue by pengc99** [aws-samples/eks-workshop-v2#663] opened 2023-09-01 20:42 UTC
### Installation method

Own AWS account

### What happened?

Building with the latest version of kubectl (1.28.1) causes the "make serve" command to fail 

### What did you expect to happen?

I expected "make serve" to work

### How can we reproduce it?

Run "make serve" with the latest version of kubectl (1.28.1)

### Anything else we need to know?

- Dropping down to 1.23.0 of kubectl will fix this as a workaround. 
- Editing all of the following kustomizations to add the "path:" statement for every "patch" section will also fix this. 

```
manifests/modules/automation/gitops/argocd/update-application/kustomization.yaml
manifests/modules/autoscaling/compute/karpenter/consolidation/kustomization.yaml
manifests/modules/autoscaling/workloads/hpa/kustomization.yaml
manifests/modules/exposing/load-balancer/ip-mode/kustomization.yaml
manifests/modules/fundamentals/affinity/checkout-redis/kustomization.yaml
manifests/modules/fundamentals/affinity/checkout/kustomization.yaml
manifests/modules/fundamentals/fargate/enabling/kustomization.yaml
manifests/modules/fundamentals/fargate/scaling/kustomization.yaml
manifests/modules/fundamentals/fargate/sizing/kustomization.yaml
manifests/modules/fundamentals/mng/taints/nodeselector-w-toleration/kustomization.yaml
manifests/modules/fundamentals/mng/taints/nodeselector-wo-toleration/kustomization.yaml
manifests/modules/fundamentals/storage/efs/deployment/kustomization.yaml
manifests/modules/introduction/kustomize/kustomization.yaml
manifests/modules/networking/custom-networking/sampleapp/kustomization.yaml
manifests/modules/networking/securitygroups-for-pods/rds/kustomization.yaml
manifests/modules/security/irsa/service-account/kustomization.yaml
manifests/modules/security/pss-psa/baseline-namespace/kustomization.yaml
manifests/modules/security/pss-psa/privileged-workload/kustomization.yaml
manifests/modules/security/pss-psa/restricted-namespace/kustomization.yaml
manifests/modules/security/pss-psa/restricted-workload/kustomization.yaml
manifests/modules/security/sealed-secrets/kustomization.yaml
```

### EKS version

n/a

**Comment by ROunofF** [comment] 2023-09-14 13:58
Duplicate of https://github.com/aws-samples/eks-workshop-v2/issues/624

**Closed by ROunofF** 2023-09-14 13:58 UTC
Labels: bug
