### ISSUE TITLE
[Bug]: Error: Failed to download module │ Could not download module "ondat"

### ISSUE THREAD

**Issue by KgomotsoWelcome** [aws-samples/eks-workshop-v2#409] opened 2023-03-30 13:06 UTC
### Installation method

Own AWS account

### What happened?

I was following the instructions for setting up the workshop on a Cloud9 instance and I am getting the error 

```
Error: Failed to download module
│ 
│ Could not download module "ondat" (.terraform/modules/cluster.eks_blueprints_kubernetes_addons/modules/kubernetes-addons/main.tf:349) source code from
│ "git::https://github.com/ondat/terraform-eksblueprints-ondat-addon?ref=0.1.2": error downloading 'https://github.com/ondat/terraform-eksblueprints-ondat-addon?ref=0.1.2': /usr/local/bin/git exited with
│ 128: Cloning into '.terraform/modules/cluster.eks_blueprints_kubernetes_addons.ondat'...
│ remote: Repository `ondat/terraform-eksblueprints-ondat-addon' is disabled.
│ remote: Please ask the owner to check their account.
│ fatal: unable to access 'https://github.com/ondat/terraform-eksblueprints-ondat-addon/': The requested URL returned error: 403
```

### What did you expect to happen?

No issue with 'ondat' module

### How can we reproduce it?

Create a Cloud9 instance and follow the instructions https://www.eksworkshop.com/docs/introduction/setup/your-account

### EKS version

terraform version
Terraform v1.4.2

**Comment by niallthomson** [comment] 2023-03-30 14:51
Thanks for reporting this. Its being caused by an upstream issue in EKS Blueprints https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/1522

A fix is in progress.

**Comment by niallthomson** [comment] 2023-03-30 16:14
This has been resolved. If you have an existing environment that is being affected by this issue please update your Terraform per the instructions here

https://www.eksworkshop.com/docs/introduction/setup/your-account#updating

**Comment by GabrielAWS** [comment] 2023-03-30 16:24
Thank you so much

**Closed** 2023-03-30 18:16 UTC
Labels: bug
